# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0573a349297ba44a1c8f4974434664daf63bd456e77e3a7784efeb71df4f2e841e8062269fec1032524d84b59c46624027943e6ddb782ebb5e7ff5a790eb0af2

test:
  secret_key_base: 8d04925e8bc68adee275cd403412b426853ae9a11160a85863d1bfa58a3fb6bb234d5374f7e26f274379af3f7cad51554653766142800b8f063c416335431ec3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
